service: boost-github-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  stage: dev
  environment:
    APP_ID: ${env:APP_ID}
    PRIVATE_KEY: ${env:PRIVATE_KEY}

functions:
  probot:
    handler: app.handler
    events:
      - http:
          path: /
          method: post
