service: boost-github-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  stage: dev
  environment:


functions:
  probot:
    handler: app.handler
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-offline
