service: boost-github-app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev
  environment:
    APP_VERSION: ${file(./package.json):version}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:us-west-2:*:table/Boost.GitHub-App.installations"
            - "arn:aws:dynamodb:us-west-2:*:table/Boost.GitHub-App.installations/index/*"
        - Effect: "Allow"
          Action:
            - secretsmanager:GetSecretValue
          Resource: "arn:aws:secretsmanager:us-west-2:*:secret:*"
        - Effect: "Allow"
          Action:
            - ses:SendEmail
          Resource:
            - "arn:aws:ses:us-west-2:507760724064:identity/monitoring@polyverse.com"
            - "arn:aws:ses:us-west-2:507760724064:identity/support@polyverse.com"

functions:
  probot:
    handler: build/app.handler
    timeout: 29 # Lambda supports 15 minutes (900 seconds), but Serverless HTTP API only 30 seconds
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-offline
